steps:
  - name: node:12
    entrypoint: npm
    args: [ "ci" ]
  - name: node:12
    entrypoint: npm
    args: [ "run", "lint" ]
  - name: node:12
    entrypoint: npm
    args: [ "run", "build" ]
  - name: "gcr.io/cloud-builders/gcloud"
    env:
      - 'REACT_APP_SERVICE_API=https://snowflake-menu-service-dot-dashboard-menu-service.ew.r.appspot.com'
    args: [ "app", "deploy" ]
timeout: "1600s"